In [166]:
import pandas as pd
import numpy as np

import re

#### Carregamento inicial dos dados no formato CSV

In [167]:
df = pd.read_csv('incidents_final_enriched.csv')
df

C:\Users\Bill_\AppData\Local\Temp/ipykernel_4300/2472686814.py:1: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('incidents_final_enriched.csv')

,Numero,Empresa,Data_de_criacao,Autoridades_comunicadas,Instalacao,Data_da_primeira_observacao,Hora_da_primeira_observacao,Data_estimada_do_incidente,Hora_do_incidente,Numero_de_feridos_graves,...,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50
0,1307/000022,OGX PETRÓLEO E GÁS S.A. (08926302000105),7/9/2013,Ministério da Previdência Social.,Ocean Quest,6/26/2013,18:20,6/26/2013,18:20,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1307/000023,PETRÓLEO BRASILEIRO S.A. (33000167000101),7/10/2013,NaN,Cerrado,7/6/2013,7:20,7/6/2013,7:20,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1307/000025,PETRÓLEO BRASILEIRO S.A. (33000167000101),7/11/2013,NaN,Ocean-Rig Corcovado,7/9/2013,12:45,7/9/2013,12:45,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1307/000026,PETRÓLEO BRASILEIRO S.A. (33000167000101),7/11/2013,NaN,OCEAN ALLIANCE,7/9/2013,18:20,7/9/2013,18:20,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1307/000027,PETRÓLEO BRASILEIRO S.A. (33000167000101),7/12/2013,IBAMA e MARINHA,SS AMAZÔNIA,6/28/2013,16:30,6/28/2013,16:30,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25641,2309/000219,KAROON PETRÓLEO E GÁS LTDA. (09347916000197),9/29/2023,NaN,FPSO CIDADE DE ITAJAÍ,5/29/2023,10:35,1/1/1900,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25642,2309/000219,KAROON PETRÓLEO E GÁS LTDA. (09347916000197),9/29/2023,NaN,FPSO CIDADE DE ITAJAÍ,5/29/2023,10:35,1/1/1900,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25643,2501/000230,SEACREST SPE CRICARÉ S.A. (35723994000159),1/30/2025,NaN,SÃO MATEUS LESTE,6/5/2023,8:00,6/5/2023,7:50,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25644,2501/000230,SEACREST SPE CRICARÉ S.A. (35723994000159),1/30/2025,NaN,SÃO MATEUS LESTE,6/5/2023,8:00,6/5/2023,7:50,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25645,2504/000126,PETRÓLEO BRASILEIRO S.A. - PETROBRAS (33000167...,4/16/2025,NaN,3-MRL-4-RJS,7/28/2022,9:31,4/8/2022,15:15,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Removendo as colunas sem nomes
<br>

##### Geralmente faço remoção de features depois de análisar o que é cada coluna, porém como são colunas com dados totalmente faltantes e sem nome, então já foi removido essas colunas.

In [168]:
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
df

,Numero,Empresa,Data_de_criacao,Autoridades_comunicadas,Instalacao,Data_da_primeira_observacao,Hora_da_primeira_observacao,Data_estimada_do_incidente,Hora_do_incidente,Numero_de_feridos_graves,Numero_de_fatalidades,Tipo_de_incidente,DSC_GRAVIDADE_TIPO,DSC_QUASE_ACIDENTE_ACIDENTE,Tipo_Instalacao_Detalhado,Proprietario_Instalacao,Fonte_Classificacao,Tipo_Instalacao
0,1307/000022,OGX PETRÓLEO E GÁS S.A. (08926302000105),7/9/2013,Ministério da Previdência Social.,Ocean Quest,6/26/2013,18:20,6/26/2013,18:20,1,0,SSM - Ferimento grave,MODERADO,Acidente,Navio de apoio logístico,Não identificado,Classificação avançada (confiança: Média) - Fr...,Navio de apoio logístico
1,1307/000023,PETRÓLEO BRASILEIRO S.A. (33000167000101),7/10/2013,NaN,Cerrado,7/6/2013,7:20,7/6/2013,7:20,1,0,SSM - Ferimento grave,MODERADO,Acidente,Outro,Não identificado,Classificação avançada (confiança: Muito Baixa...,Outro
2,1307/000025,PETRÓLEO BRASILEIRO S.A. (33000167000101),7/11/2013,NaN,Ocean-Rig Corcovado,7/9/2013,12:45,7/9/2013,12:45,0,0,SSM - Princípio de incêndio,LEVE,Acidente,Sonda de Perfuração,Ocean Rig,https://pt.linkedin.com/posts/venicio-viter-a7...,Sonda de perfuração
3,1307/000026,PETRÓLEO BRASILEIRO S.A. (33000167000101),7/11/2013,NaN,OCEAN ALLIANCE,7/9/2013,18:20,7/9/2013,18:20,1,0,SSM - Ferimento grave,MODERADO,Acidente,Navio de apoio logístico,Não identificado,Classificação avançada (confiança: Média) - Fr...,Navio de apoio logístico
4,1307/000027,PETRÓLEO BRASILEIRO S.A. (33000167000101),7/12/2013,IBAMA e MARINHA,SS AMAZÔNIA,6/28/2013,16:30,6/28/2013,16:30,0,0,SSM - Descarga menor de óleo,LEVE,Acidente,Sonda de perfuração,Baerfield Drilling LLC,https://www.gov.br/mme/pt-br/arquivos/do-29-09...,Sonda de perfuração
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25641,2309/000219,KAROON PETRÓLEO E GÁS LTDA. (09347916000197),9/29/2023,NaN,FPSO CIDADE DE ITAJAÍ,5/29/2023,10:35,1/1/1900,NaN,0,0,SSM - Falha estrutural em tanque,GRAVE,Acidente,FPSO,SBM Offshore (afretado pela Petrobras),https://www.sbmoffshore.com/,FPSO
25642,2309/000219,KAROON PETRÓLEO E GÁS LTDA. (09347916000197),9/29/2023,NaN,FPSO CIDADE DE ITAJAÍ,5/29/2023,10:35,1/1/1900,NaN,0,0,SSM - Perda de contenção primária maior de águ...,LEVE,Quase acidente,FPSO,SBM Offshore (afretado pela Petrobras),https://www.sbmoffshore.com/,FPSO
25643,2501/000230,SEACREST SPE CRICARÉ S.A. (35723994000159),1/30/2025,NaN,SÃO MATEUS LESTE,6/5/2023,8:00,6/5/2023,7:50,0,0,SSM - Descarga significante de óleo,MODERADO,Acidente,Outro,Não identificado,Classificação avançada (confiança: Muito Baixa...,Outro
25644,2501/000230,SEACREST SPE CRICARÉ S.A. (35723994000159),1/30/2025,NaN,SÃO MATEUS LESTE,6/5/2023,8:00,6/5/2023,7:50,0,0,SSM - Perda de contenção primária significante...,LEVE,Quase acidente,Outro,Não identificado,Classificação avançada (confiança: Muito Baixa...,Outro
25645,2504/000126,PETRÓLEO BRASILEIRO S.A. - PETROBRAS (33000167...,4/16/2025,NaN,3-MRL-4-RJS,7/28/2022,9:31,4/8/2022,15:15,0,0,SSM - Falha de elemento do conjunto solidário ...,LEVE,Quase acidente,Outro,Não identificado,Classificação avançada (confiança: Muito Baixa...,Outro

### Descrição das Colunas do Dataset
<br>

### Visão Geral
Dataset contendo registros de incidentes e quase acidentes em instalações offshore de petróleo e gás no Brasil.

---

### Descrição Detalhada das Colunas

<br>

#### **Numero**
- **Descrição**: Número único de identificação do registro do incidente

#### **Empresa**
- **Descrição**: Empresa operadora ou responsável pela instalação

#### **Data_de_criacao**
- **Descrição**: Data de criação do registro no sistema

#### **Autoridades_comunicadas**
- **Descrição**: Órgãos e autoridades notificadas sobre o incidente

#### **Instalacao**
- **Descrição**: Nome da instalação ou equipamento onde ocorreu o incidente

#### **Data_da_primeira_observacao**
- **Descrição**: Data da primeira observação do incidente

#### **Hora_da_primeira_observacao**
- **Descrição**: Hora da primeira observação do incidente

#### **Data_estimada_do_incidente**
Data estimada em que o incidente ocorreu

#### **Hora_do_incidente**
- **Descrição**: Hora estimada do incidente

#### **Numero_de_feridos_graves**
- **Descrição**: Quantidade de pessoas com ferimentos graves

#### **Numero_de_fatalidades**
- **Descrição**: Número de mortes resultantes do incidente

#### **Tipo_de_incidente**
- **Descrição**: Classificação específica do tipo de incidente

#### **DSC_GRAVIDADE_TIPO**
- **Descrição**: Classificação da gravidade do incidente

#### **DSC_QUASE_ACIDENTE_ACIDENTE**
- **Descrição**: Distinção entre acidente real e quase acidente

#### **Tipo_Instalacao_Detalhado**
- **Descrição**: Descrição detalhada do tipo de instalação

#### **Proprietario_Instalacao**
- **Descrição**: Empresa proprietária da instalação

#### **Fonte_Classificacao**
- **Descrição**: Fonte utilizada para classificar o incidente

#### **Tipo_Instalacao**
- **Descrição**: Categoria geral do tipo de instalação

---

In [169]:
# Criando DataFrame a modificar
df_analysis = df.copy()

In [170]:
(df_analysis.isnull().sum()/len(df_analysis))*100

Numero                          0.000000
Empresa                         0.000000
Data_de_criacao                 0.000000
Autoridades_comunicadas        85.019106
Instalacao                      0.257350
Data_da_primeira_observacao     0.249552
Hora_da_primeira_observacao     0.257350
Data_estimada_do_incidente      0.253451
Hora_do_incidente              11.713328
Numero_de_feridos_graves        0.245652
Numero_de_fatalidades           0.222257
Tipo_de_incidente               0.023395
DSC_GRAVIDADE_TIPO              9.303595
DSC_QUASE_ACIDENTE_ACIDENTE     9.303595
Tipo_Instalacao_Detalhado       0.206660
Proprietario_Instalacao         0.206660
Fonte_Classificacao             0.206660
Tipo_Instalacao                 0.198861
dtype: float64

# Revisão de Features

## Datas
<br>

#### Foi unido as datas e horários, alterado para o tipo data para fazer análise temporal e removido as que estavam no formato texto.

In [171]:
# Combinar data + hora para criar uma nova coluna datetime completo
df_analysis['DataHora_primeira_observacao'] = pd.to_datetime(
    df_analysis['Data_da_primeira_observacao'].astype(str) + ' ' + df_analysis['Hora_da_primeira_observacao'].astype(str),
    errors='coerce'
)
df_analysis['DataHora_incidente'] = pd.to_datetime(
    df_analysis['Data_estimada_do_incidente'].astype(str) + ' ' + df_analysis['Hora_do_incidente'].astype(str),
    errors='coerce'
)

# Transformando a coluna para o tipo data
df_analysis['Data_de_criacao'] = pd.to_datetime(df_analysis['Data_de_criacao'], errors='coerce')

# Removendo as colunas que foram usadas para criar as novas colunas (pra não ficar repetido)
df_analysis = df_analysis.drop([
    'Data_da_primeira_observacao',
    'Hora_da_primeira_observacao',
    'Data_estimada_do_incidente',
    'Hora_do_incidente'], axis=1)

### Valor Minimo
<br>

#### Ao explorar um pouco os valores, percebi que a coluna DataHora_incidente tem um valor do ano de 1900 e outro de 1985, esses valores podem ser reais, seria interessante verificar junto a empresa que preencheu sobre a confiabilidade dessa informação, porém é muito estranho, pois após esses dois valores há um salto pro ano de 2011, então leva a crer que são valores errados e que podem impactar muito na análise temporal, então esses dois valores vão ser transformados em NaNs, entendendo que não são valores a serem levados em consideração.

#### Além disso tem uma única linha com ano de 2011, que vai impactar no momento da anáise, para ter uma ideia anual é necessário vários registros, então esse dado vai ser passado para 2012.

In [172]:
# Alterando a única linha que é 2011 para 2012
df_analysis.loc[df_analysis['DataHora_incidente'].dt.year == 2011, 'DataHora_incidente'] = \
    df_analysis.loc[df_analysis['DataHora_incidente'].dt.year == 2011, 'DataHora_incidente'].apply(
        lambda x: x.replace(year=2012)
    )

In [173]:
# Alterando essas linhas que estão com datas extremas para valores vazios
df_analysis.loc[22564, 'DataHora_incidente'] = pd.NaT
df_analysis.loc[14519, 'DataHora_incidente'] = pd.NaT

### Valores faltantes
<br>

#### Para os valores faltantes, vou usar as linhas que tem alguma data preenchida para copiar para a coluna que está com o dado faltante, assim é possível que se aproxime bem ao valor real e não deixa com o dado faltante.
<br>

#### A lógica vai ser: 
#### DataHora_primeira_observacao (COPIA) de Data_de_criacao
#### DataHora_incidente (COPIA) de DataHora_primeira_observacao
<br>

#### Escolhi essa lógica porque a DataHora_primeira_observacao tem 68 dados faltantes e a DataHora_incidente tem 3010, além disso a DataHora_incidente é mais próxima a primeira observação do que a de criação.

In [174]:
# Substituindo os valores NaN de DataHora_primeira_observacao pelos valores de Data_de_criacao
df_analysis['DataHora_primeira_observacao'] = df_analysis['DataHora_primeira_observacao'].fillna(
    df_analysis['Data_de_criacao']
)

# Substituindo os valores NaN de DataHora_incidente pelos valores de DataHora_primeira_observacao
df_analysis['DataHora_incidente'] = df_analysis['DataHora_incidente'].fillna(
    df_analysis['DataHora_primeira_observacao']
)

## Numero
<br>

#### Numero: É como se fosse o ID do acidente, seu formato pode ser mantido do tipo texto, ainda mais pelo uso de "/" para separar os números. Não foi necessário fazer nenhuma alteração.

## Empresa
<br>

#### Algumas empresas estão com o nome diferente, porém tem o mesmo código de identificação na frente, mostrando que são na realidade da mesma empresa. Isso pode significar que seja de um polo diferente ou pode ser um registro duplo, que pode fracionar as informações e levar uma análise equivocada.
<br>

#### Como a empresa pode estar com nome antigo, fantasia, ter mais de um nome, etc... Resolvi por deixar apenas o CNPJ e remover o nome da empresa, dessa forma esses dados podem ser agrupados a um único CNPJ.

#### As linhas mostradas abaixo não tem o nome ou CNPJ das empresas, achei esses valores após ter criado a coluna CNPJ e perceber que ficou com valores nulos (pois não tinham o CNPJ como padrão entre parenteses), mas todos tem como padrão o valor de 	"4.40237E+13" que é uma notação ciêntifica e tem suas instalações preenchidas, então da pra usar um documento fornecido pela ANP(Agência Nacional do Petróleo, Gás Natural e Biocombustíveis) para associar a instalação a empresa e depois verificar usando serasa experian.
<br>

#### Documento ANP: https://www.gov.br/anp/pt-br/assuntos/exploracao-e-producao-de-oleo-e-gas/desenvolvimento-e-producao/arquivos-lista-de-codigos/codigo-instalacoes.csv
<br>

#### Portal Serasa Experian: https://empresas.serasaexperian.com.br/consulta-gratis

In [175]:
# Mostrando empresas que não foram identificadas e não tem o CNPJ preenchido
df_analysis[df_analysis["Empresa"] == "4.40237E+13"][["Empresa", "Instalacao"]]

          Empresa                                         Instalacao
6038  4.40237E+13  Unidade de Compressão de Gás Natural do Campo ...
6402  4.40237E+13                     Estação Coletora João de Barro
6403  4.40237E+13                         Estação coletora Periquito
6404  4.40237E+13                         Estação coletora Periquito
6405  4.40237E+13                         Estação coletora Periquito
6406  4.40237E+13                           Estação Coletora Concriz
6408  4.40237E+13           Campo Galo de Campina - Poço 3-UTC-5A-RN
6409  4.40237E+13                   Estação Coletora Galo de Campina
6418  4.40237E+13            Campo João de Barro - Poço 4-AURI-15-RN
6419  4.40237E+13            Campo João de Barro - Poço 4-AURI-15-RN
6420  4.40237E+13                   Estação Coletora Galo de Campina
6421  4.40237E+13                   Estação Coletora Galo de Campina
6422  4.40237E+13                   Estação Coletora Galo de Campina
6896  4.40237E+13                 3-AURI-09-RN (Campo João de Barro)
6972  4.40237E+13                         Estação coletora Periquito

#### Aqui foi feito um dicionário onde a chave é o valor da coluna Instalacao e o valor foi pego na pesquisa do documento disponibilizado pela ANP.
<br>

#### Logo depois é aplicado função que compara os valores da chave do dicionário com os valores da coluna Instalacao e muda o valor dessa linha na coluna Empresa pelo valor do dicionário.

In [176]:
# Criando valores para as linhas que não tem valor valido na coluna Empresa.
mapa_empresa = {
    "Unidade de Compressão de Gás Natural do Campo de Graúna": 
        "PHOENIX ÓLEO & GÁS NATURAL LTDA. (32528443000146)",

    "Estação Coletora João de Barro": 
        "NÍON ENERGIA S.A. (45832752000157)",

    "Estação coletora Periquito": 
        "PHOENIX EMPREENDIMENTOS LTDA. (05282436000134)",

    "Estação Coletora Concriz": 
        "PHOENIX EMPREENDIMENTOS LTDA. (05282436000134)",

    "Campo Galo de Campina - Poço 3-UTC-5A-RN": 
        "NÍON ENERGIA S.A. (45832752000157)",

    "Estação Coletora Galo de Campina": 
        "NÍON ENERGIA S.A. (45832752000157)",

    "Campo João de Barro - Poço 4-AURI-15-RN": 
        "NÍON ENERGIA S.A. (45832752000157)",

    "3-AURI-09-RN (Campo João de Barro)": 
        "NÍON ENERGIA S.A. (45832752000157)",
}

# Preenche os valores da coluna Empresa de acordo com o mapa_empresa criado antes que tem como chave a Instalação
df_analysis['Empresa'] = df_analysis.apply(
    lambda row: mapa_empresa.get(row['Instalacao'], row['Empresa']),
    axis=1
)

In [177]:
# Criando a coluna CNPJ que vai conter apenas o código que está entre parenteses
df_analysis['CNPJ'] = df_analysis['Empresa'].str.extract(r'\((\d+)\)')

# Verificando quantas empresas tem valores repetidos
df_analysis.groupby('CNPJ')['Empresa'].nunique().sort_values(ascending=False)

CNPJ
52127214000127    4
02031413000169    3
11230625000166    3
11058804000168    3
08926302000105    3
04028583000110    2
34812047000171    2
34186669000131    2
33000167000101    2
23018639000108    2
05002889000160    2
04580657000126    2
11253257000171    2
02461767000143    2
04033958000130    1
02270689000108    1
30759670000157    1
32021201000161    1
32528443000146    1
33337122000127    1
33443860000159    1
33453598000123    1
33639843000191    1
02031413000320    1
24219122000131    1
35156290000141    1
35723994000159    1
36093991000141    1
40254927000172    1
40768701000190    1
41955491000101    1
44186763000144    1
45832752000157    1
24414030000102    1
02857854000114    1
04423567000121    1
09347916000197    1
04494968000172    1
03951809000197    1
03571723000139    1
05282436000134    1
06235572000136    1
08584563000186    1
03347723000150    1
09309027000135    1
10456016000167    1
16607122000180    1
03342704000130    1
11230122000190    1
03255266000173    1
02873528000109    1
11944627000117    1
12456210000178    1
13612806000182    1
15240822000117    1
00271847000100    1
Name: Empresa, dtype: int64

In [178]:
# Removendo a coluna "Empresa", pois já tem a nova coluna CNPJ para identifica-las
df_analysis.drop(columns=['Empresa'], inplace=True)

## Autoridades_comunicadas
<br>

#### Essa coluna está muito ruim, o grande problema dela é que ao invés de deixar selecionar apenas opções já pré estabelecidas, o usuário pode colocar qualquer coisa, então tem 893 valores diferentes e pra piorar 85% das linhas dessa feature estão vazias. Então ela será removida do df_analysis, se por ventura ser possível usar os poucos dados dessa coluna, então elas podem ser re-inseridas através do dataframe df.

In [179]:
# Removendo a coluna
df_analysis.drop(columns=['Autoridades_comunicadas'], inplace=True)

## Instalacao
<br>

#### A instalação também tem problema do usuário preencher livremente, então novamente temos as mesmas Instalações porém com nomes diferentes, como não existe um padrão, não tem como dar uma solução que seja 100%, mesmo se os nomes que usam números romanos fossem passados para arábicos, ainda teriam muitas variações, mas pelo menos nessa coluna tem apenas 0.25% linhas faltantes e existe um padrão minimo, então já da pra ajudar em alguma coisa.

#### Para que não haja impactos na análise, preenchi os valores vazios como "Não preenchidos".

In [180]:
# Preenchendo NaNs
df_analysis["Instalacao"] = df_analysis["Instalacao"].fillna("Não preenchidos")

## Numero_de_feridos_graves
<br>

#### Essa coluna tem alguns valores que não tem haver com a quantidade de feridos graves, como data/hora, NaN(valor vazio), e espaço em branco ' '. Então basta retirar esses valores que não tem haver e preencher o NaN com 0 que é a moda, sendo que tem apenas 0.24% de valores NaN, dessa forma vai ficar tudo certo com a coluna e não vai ter nenhum impacto por esse preenchimento.

In [181]:
# Verificando cada tipo de valor que tem na coluna e suas respectivas quantidades
df_analysis['Numero_de_feridos_graves'].value_counts()

Numero_de_feridos_graves
0             24991
1               559
2                19
7                 4
3                 3
5                 1
19                1
10/18/2019        1
8/7/2021          1
                  1
8:50              1
2:22              1
Name: count, dtype: int64

In [182]:
# Transforma tudo que for possível para numérico e o que da erro vai virar NaN
df_analysis['Numero_de_feridos_graves'] = pd.to_numeric(
    df_analysis['Numero_de_feridos_graves'], errors='coerce'
)

# Transforma tudo que é NaN em 0 que é a moda com uma quantidade muito maior
df_analysis['Numero_de_feridos_graves'] = (
    df_analysis['Numero_de_feridos_graves']
    .fillna(0)
    .astype(int)
)

## Tipo_de_incidente
<br>

####  Essa coluna está bem padronizada, ainda assim tem muitos valores diferentes, sendo 186 tipos, não da pra ter certeza se foi usado um tipo de seleção restrita para o usuário ou apenas foi bem padronizado por responsáveis da inclusão dessa informação. Então para focar apenas em informações mais confiaveis, foi deixado apenas os preenchimentos com SSM na frente, preenchidos pela Segurança, Saúde e Meio Ambiente, o restante foram preenchidos como "Informação não padronizada".

In [183]:
df_analysis['Tipo_de_incidente'].str.startswith('SSM').sum()

19327

In [184]:
# Alterando os valores NaN e outros aleatórios por "Informação não padronizada"
df_analysis['Tipo_de_incidente'] = (
    df_analysis['Tipo_de_incidente']
    .fillna("Informação não padronizada")
    .where(lambda s: s.str.startswith("SSM"), "Informação não padronizada")
)

## Numero_de_fatalidades
<br>

#### Muito similar ao feridos graves, algumas informações que não tem sentido com o que a coluna está pedindo, então será usado a mesma estratégia, transformar o que é número em número, o resto vira NaN e depois os NaN vão virar a moda.

In [185]:
# Verificando cada tipo de valor que tem na coluna e suas respectivas quantidades
df_analysis['Numero_de_fatalidades'].value_counts()

Numero_de_fatalidades
0                                     25534
1                                        35
9                                         4
                                          4
2                                         3
3                                         3
 ANP/SSM (antiga ANP/CSO)                 1
 Instituto do Meio Ambiente (INEA)        1
6:40                                      1
5:20                                      1
FPSO CIDADE DE VITÓRIA                    1
3/27/2022                                 1
Name: count, dtype: int64

In [186]:
# Transforma tudo que for possível para numérico e o que da erro vai virar NaN
df_analysis['Numero_de_fatalidades'] = pd.to_numeric(
    df_analysis['Numero_de_fatalidades'], errors='coerce'
)

# Transforma tudo que é NaN em 0 que é a moda com uma quantidade muito maior
df_analysis['Numero_de_fatalidades'] = (
    df_analysis['Numero_de_fatalidades']
    .fillna(0)
    .astype(int)
)

## DSC_GRAVIDADE_TIPO
<br>

#### Novamente um problema bem similar onde a coluna tem alguns valores inválidos, sendo os únicos validos LEVE, MODERADO E GRAVE, então os demais valores vão ser transformados na moda novamente.

In [187]:
# Verificando cada tipo de valor que tem na coluna e suas respectivas quantidades
df_analysis['DSC_GRAVIDADE_TIPO'].value_counts()

DSC_GRAVIDADE_TIPO
LEVE                                                                           20317
MODERADO                                                                        2693
GRAVE                                                                            233
2/1/2022                                                                           2
 MARINHA DL/CP - MACAÉ RJ                                                          2
8/13/2021                                                                          1
0                                                                                  1
1/31/2022                                                                          1
PETROBRAS 54                                                                       1
13:14                                                                              1
6:40                                                                               1
5:20                                                                               1
PETROBRAS 50                                                                       1
PETROBRAS 31                                                                       1
PETROBRAS 09                                                                       1
PLATAFORMA DE PARGO-1B                                                             1
PETROBRAS 19                                                                       1
Descarga menor de fluido de perfuração, completação ou intervenção em poços        1
Name: count, dtype: int64

In [188]:
# Atribuindo a moda a variável moda
moda = df_analysis['DSC_GRAVIDADE_TIPO'].mode()[0]

# Alterando todos valores inadequados com a moda
df_analysis['DSC_GRAVIDADE_TIPO'] = df_analysis['DSC_GRAVIDADE_TIPO'].apply(
    lambda x: x if x in ['LEVE', 'MODERADO', 'GRAVE'] else moda
)

## DSC_QUASE_ACIDENTE_ACIDENTE
<br>

#### A coluna de quase acidente também infrenta o problema de alguns valores preenchidos de forma errada, mas ao verificar a quantidade de cada valor da pra perceber que deveria ser preenchido um "Quase acidente" ou de fato um "Acidente", os demais valores parecem não ser validos, então serão transformados em moda novamente.

In [189]:
# Verificando cada tipo de valor que tem na coluna e suas respectivas quantidades
df_analysis['DSC_QUASE_ACIDENTE_ACIDENTE'].value_counts()

DSC_QUASE_ACIDENTE_ACIDENTE
Quase acidente            15749
Acidente                   7494
0                             3
 INEA Campos e INEA RJ        2
20:18                         2
5/6/2016                      1
7/21/2016                     1
5/2/2016                      1
4/11/2018                     1
2/13/2019                     1
15:44                         1
10/5/2021                     1
12/29/2021                    1
13:53                         1
LEVE                          1
Name: count, dtype: int64

In [190]:
# Atribuindo a moda a variável moda
moda = df_analysis['DSC_QUASE_ACIDENTE_ACIDENTE'].mode()[0]

# Alterando todos valores inadequados com a moda
df_analysis['DSC_QUASE_ACIDENTE_ACIDENTE'] = df_analysis['DSC_QUASE_ACIDENTE_ACIDENTE'].apply(
    lambda x: x if x in ['Quase acidente', 'Acidente'] else moda
)

## Tipo_Instalacao_Detalhado
<br>

#### A coluna Tipo_Instalacao_Detalhado é um pouco similar as colunas onde tinham alguns valores inadequados e foram preenchidos pela moda, aqui também tiveram valores incorretos, porém para alterar esses valores foi necessário olhar valor por valor e ver qual tinha alguma relação com a proposta da coluna e qual foi preenchido completamente errado, então fiz a alteração de forma bem arbitraria e ao invés de substituir pela moda que é FPSO, substitui pelo valor "Outro", já que não tem como eu saber ao certo o tipo de instalação e dessa forma eu deixo em aberto o que poderia ter sido.

In [191]:
# Verificando cada tipo de valor que tem na coluna e suas respectivas quantidades
df_analysis['Tipo_Instalacao_Detalhado'].value_counts()

Tipo_Instalacao_Detalhado
FPSO                                                         9280
Outro                                                        8267
Plataforma Fixa                                              2130
Sonda de perfuração                                          2046
Plataforma Semi-submersível de Produção                      1552
Navio de apoio logístico                                      558
Navio de atividade subsea                                     403
Terminal/Estação                                              316
Campo de Petróleo                                             291
Plataforma Fixa de Gás                                        251
Embarcação                                                    231
Plataforma de Cabeça de Poço                                  212
Plataforma Fixa de Produção                                    21
Sonda de Perfuração                                            17
Navio de estimulação de poços                                   2
2/1/2022                                                        2
0                                                               2
8/2/2021                                                        1
Falha de elemento do conjunto solidário de barreira (CSB)       1
1/18/2022                                                       1
13:10                                                           1
13:14                                                           1
10:20                                                           1
15:05                                                           1
14:00                                                           1
9:10                                                            1
9:45                                                            1
Terminal Portuário                                              1
Acidente                                                        1
Name: count, dtype: int64

In [192]:
# Lista de valores inválidos que devem virar "Outro"
valores_invalidos = [
    '2/1/2022', '0', '8/2/2021',
    'Falha de elemento do conjunto solidário de barreira (CSB)',
    '1/18/2022', '13:10', '13:14', '10:20', '15:05',
    '14:00', '9:10', '9:45', 'Acidente'
]

# Substitui os valores invalidos e os NaN por "Outro"
df_analysis['Tipo_Instalacao_Detalhado'] = (
    df_analysis['Tipo_Instalacao_Detalhado']
    .replace(valores_invalidos, "Outro")
    .fillna("Outro")
)

## Proprietario_Instalacao

In [193]:
# Verificando cada tipo de valor que tem na coluna e suas respectivas quantidades
df_analysis['Proprietario_Instalacao'].value_counts()

Proprietario_Instalacao
Petrobras                                             11144
Não identificado                                       9099
SBM Offshore (afretado pela Petrobras)                 1967
Seadrill                                                458
Ocyan (ex-Odebrecht Oil & Gas)                          445
Ensco                                                   328
PetroRio (ex-Chevron/Petrobras)                         269
DOF Subsea Brasil                                       193
Petrobras Netherlands B.V.                              191
Ocean Rig                                               185
SBM Offshore / Petrobras (operador)                     168
Equinor / BW Offshore (operador)                        158
Noble Corporation                                       130
MODEC (operado pela Petrobras)                          127
Transocean                                              122
Sevan Drilling                                          118
Subsea 7                                                 96
Constellation / Petrobras (operador)                     72
Odfjell Drilling                                         62
Solstad Offshore                                         39
Aban Offshore                                            34
Pride International                                      29
Baerfield Drilling LLC                                   28
Ocyan (anteriormente Odebrecht)                          26
Seacor                                                   21
BW Offshore / Petrobras (operador)                       20
Maersk Drilling                                          15
Maersk / Equinor (operador)                              10
ENSCO                                                     6
Não Aplicável / Desconhecido                              5
Drill Ship International B.V.                             4
Farstad Shipping (agora Solstad Offshore)                 2
0:00                                                      2
Galliano Marine Services / Edison Chouest Offshore        2
20:18                                                     2
UP Offshore                                               2
Outro                                                     1
Solstad Maritime                                          1
LEVE                                                      1
12/29/2021                                                1
0                                                         1
SSM - Descarga menor de óleo                              1
SSM - Princípio de incêndio                               1
2/13/2019                                                 1
4/11/2018                                                 1
5/2/2016                                                  1
7/21/2016                                                 1
5/6/2016                                                  1
EMAS AMC                                                  1
Ocyan (ex-Odebrecht)                                      1
Name: count, dtype: int64

In [194]:
# Listando de valores inválidos que devem virar "Não identificado"
invalidos = [
    "Não Aplicável / Desconhecido",
    "0:00",
    "20:18",
    "Outro",
    "LEVE",
    "12/29/2021",
    "0",
    "SSM - Descarga menor de óleo",
    "SSM - Princípio de incêndio",
    "2/13/2019",
    "4/11/2018",
    "5/2/2016",
    "7/21/2016",
    "5/6/2016"
]

# Substituindo valores inválidos
df_analysis["Proprietario_Instalacao"] = (
    df_analysis["Proprietario_Instalacao"]
    .replace(invalidos, "Não identificado")
    .fillna("Não identificado")
)

# Unificando as duas versões inconsistentes da Ocyan Odebrecht
df_analysis["Proprietario_Instalacao"] = (
    df_analysis["Proprietario_Instalacao"]
    .replace({
        "Ocyan (anteriormente Odebrecht)": "Ocyan (ex-Odebrecht Oil & Gas)",
        "Ocyan (ex-Odebrecht)": "Ocyan (ex-Odebrecht Oil & Gas)"
    })
)

## Fonte_Classificacao
<br>

#### Muito similar as outras colunas, aqui foi tirado alguns valores como horário ou valores que deveriam estar em outra coluna e atribuido o valor de "Não identificado" a eles, não muda muita coisa, foram poucos valores, mas pelo menos foi levemente arrumado.

In [195]:
# Ajuste para mostrar mais linhas e poder ver os valores
pd.set_option('display.max_rows', 80)
# Verificando cada tipo de valor que tem na coluna e suas respectivas quantidades
df_analysis['Fonte_Classificacao'].value_counts()

Fonte_Classificacao
Classificação avançada (confiança: Muito Baixa) - Freq: 1    2165
Classificação automática melhorada (confiança: Alta)         1218
Busca web - padrão série Petrobras                           1026
https://www.marinha.mil.br/dpc/                               921
Classificação avançada (confiança: Muito Baixa) - Freq: 2     828
                                                             ...
15:05                                                           1
9:10                                                            1
14:00                                                           1
10:20                                                           1
Não identificado                                                1
Name: count, Length: 215, dtype: int64

In [196]:
valores_substituir = [
    "0",
    "Pesquisa na internet não retornou informações sobre instalação de óleo e gás com este nome.",
    "LEVE",
    "9:45",
    "Quase acidente",
    "13:10",
    "15:05",
    "9:10",
    "14:00",
    "10:20"
]

df_analysis['Fonte_Classificacao'] = (
    df_analysis['Fonte_Classificacao']
        .replace(valores_substituir, "Não identificado")
        .fillna("Não identificado")
)

## Tipo_Instalacao
<br>

#### Essa coluna é praticamente identica a coluna Tipo_Instalacao_Detalhado, porém com menos valores preenchidos, então fiz a remoção dessa coluna, para não ter ambiguidade e colineariedade na análise.

In [197]:
df_analysis = df_analysis.drop(['Tipo_Instalacao'], axis=1)

## Categoria_Custo
<br>

#### Criação da coluna Categoria_Custo para poder mensurar valor gasto em incidentes.

In [198]:
# Dicionário COMPLETO de mapeamento - TODOS OS 93 INCIDENTES
mapeamento_completo = {
    # ========== DANOS A SAÚDE ==========
    'SSM - Ferimento grave': 'Danos a Saúde',
    'SSM - Fatalidade': 'Danos a Saúde',
    'SSM - Homem ao mar': 'Danos a Saúde',
    'SSM - Ferimento com afastamento por mais de 3 (três) dias': 'Danos a Saúde',
    'SSM - Ferimento com afastamento de 1 (um) a 3 (três) dias': 'Danos a Saúde',
    'SSM - Surto de doença infectocontagiosa ou transmitida por alimentos': 'Danos a Saúde',
    'SSM - Quase acidente de alto potencial': 'Danos a Saúde',  # Near miss com alto risco à vida
    
    # ========== PERDA DE CONTROLE/CRÍTICO ==========
    'SSM - Falha da barreira primária na perfuração ou intervenção em poços (kick)': 'Perda de Controle/Critico',
    'SSM - Falha no Blowout Preventer (BOP)': 'Perda de Controle/Critico',
    'SSM - Perda de contenção de H2S': 'Perda de Controle/Critico',
    'SSM - Vazamento de H2S': 'Perda de Controle/Critico',
    'SSM - Perda significante de controle de poço': 'Perda de Controle/Critico',
    'SSM - Perda maior de controle de poço': 'Perda de Controle/Critico',
    'SSM - Perda menor de controle de poço': 'Perda de Controle/Critico',
    'SSM - Falha de elemento do conjunto solidário de barreira (CSB)': 'Perda de Controle/Critico',
    'SSM - Parâmetro de monitoramento de CSB fora do limite de projeto': 'Perda de Controle/Critico',
    'SSM - Aprisionamento de coluna': 'Perda de Controle/Critico',
    'SSM - Perda de circulação': 'Perda de Controle/Critico',
    
    # ========== CUSTOS AMBIENTAIS ==========
    'SSM - Descarga menor de óleo': 'Custos Ambientais',
    'SSM - Descarga significante de óleo': 'Custos Ambientais',
    'SSM - Descarga maior de óleo': 'Custos Ambientais',
    'SSM - Perda de contenção primária significante de óleo': 'Custos Ambientais',
    'SSM - Perda de contenção primária maior de óleo': 'Custos Ambientais',
    'SSM - Descarga menor de água oleosa': 'Custos Ambientais',
    'SSM - Descarga significante de água oleosa': 'Custos Ambientais',
    'SSM - Descarga maior de água oleosa': 'Custos Ambientais',
    'SSM - Perda de contenção primária significante de água oleosa': 'Custos Ambientais',
    'SSM - Perda de contenção primária maior de água oleosa': 'Custos Ambientais',
    'SSM - Descarga menor de água produzida': 'Custos Ambientais',
    'SSM - Descarga significante de água produzida': 'Custos Ambientais',
    'SSM - Descarga maior de água produzida': 'Custos Ambientais',
    'SSM - Perda de contenção primária significante de água produzida': 'Custos Ambientais',
    'SSM - Perda de contenção primária maior de água produzida': 'Custos Ambientais',
    'SSM - Descarga menor de água de injeção': 'Custos Ambientais',
    'SSM - Descarga significante de água de injeção': 'Custos Ambientais',
    'SSM - Descarga maior de água de injeção': 'Custos Ambientais',
    'SSM - Perda de contenção primária significante de água de injeção': 'Custos Ambientais',
    'SSM - Perda de contenção primária maior de água de injeção': 'Custos Ambientais',
    'SSM - Descarga menor de fluido de perfuração, completação ou intervenção em poços': 'Custos Ambientais',
    'SSM - Descarga significante de fluido de perfuração, completação ou intervenção em poços': 'Custos Ambientais',
    'SSM - Descarga maior de fluido de perfuração, completação ou intervenção em poços': 'Custos Ambientais',
    'SSM - Perda de contenção primária significante de fluido de perfuração, completação ou intervenção em poços': 'Custos Ambientais',
    'SSM - Perda de contenção primária maior de fluido de perfuração, completação ou intervenção em poços': 'Custos Ambientais',
    'SSM - Descarga menor de material com alto potencial de dano': 'Custos Ambientais',
    'SSM - Descarga significante de material com alto potencial de dano': 'Custos Ambientais',
    'SSM - Descarga maior de material com alto potencial de dano': 'Custos Ambientais',
    'SSM - Perda de contenção primária significante de material com alto potencial de dano': 'Custos Ambientais',
    'SSM - Perda de contenção primária maior de material com alto potencial de dano': 'Custos Ambientais',
    'SSM - Descarga menor de substância nociva ou perigosa': 'Custos Ambientais',
    'SSM - Descarga significante de substância nociva ou perigosa': 'Custos Ambientais',
    'SSM - Descarga maior de substância nociva ou perigosa': 'Custos Ambientais',
    'SSM - Perda de contenção primária significante de substância nociva ou perigosa': 'Custos Ambientais',
    'SSM - Perda de contenção primária maior de substância nociva ou perigosa': 'Custos Ambientais',
    'SSM - Perda de contenção significante de gás inflamável': 'Custos Ambientais',
    'SSM - Perda de contenção maior de gás inflamável': 'Custos Ambientais',
    'SSM - Vazamento maior de gás inflamável': 'Custos Ambientais',
    'SSM - Vazamento significante de gás inflamável': 'Custos Ambientais',
    'SSM - Perda de fonte radioativa': 'Custos Ambientais',  # Contaminação radioativa
    'SSM - Descarte fora de especificação de água produzida': 'Custos Ambientais',
    'SSM - Descarte fora de especificação de fluidos de perfuração, completação, intervenção ou cascalhos': 'Custos Ambientais',
    'SSM - Constatação de mancha de origem indeterminada': 'Custos Ambientais',
    'SSM - Queima ou emissão de gás por motivo de emergência': 'Custos Ambientais',  # Emissão atmosférica
    
    # ========== DANOS A EQUIPAMENTOS ==========
    'SSM - Queda de objetos': 'Danos a Equipamentos',
    'SSM - Afundamento de equipamento ou material': 'Danos a Equipamentos',
    'SSM - Falha do sistema de ancoragem': 'Danos a Equipamentos',
    'SSM - Falha estrutural em instalação offshore': 'Danos a Equipamentos',
    'SSM - Falha estrutural em poço': 'Danos a Equipamentos',
    'SSM - Falha estrutural em sistema de coleta ou escoamento da produção': 'Danos a Equipamentos',
    'SSM - Falha estrutural em tanque': 'Danos a Equipamentos',
    'SSM - Queda no mar de equipamento ou material': 'Danos a Equipamentos',
    'SSM - Queda de helicóptero': 'Danos a Equipamentos',
    'SSM - Abalroamento significante': 'Danos a Equipamentos',
    'SSM - Adernamento': 'Danos a Equipamentos',  # Colisão de embarcações
    'SSM - Falha no riser de perfuração ou intervenção': 'Danos a Equipamentos',
    'SSM - Desconexão de emergência': 'Danos a Equipamentos',
    'SSM - Perda de posicionamento': 'Danos a Equipamentos',  # Plataforma offshore
    
    # ========== DOWNTIME ==========
    'SSM - Interrupção não programada superior a 24 (vinte e quatro) horas decorrente de incidente operacional': 'Downtime',
    'SSM - Interrupção não programada superior a 24 (vinte e quatro) horas': 'Downtime',
    'SSM - Parada emergencial de nível menor': 'Downtime',
    'SSM - Parada emergencial de planta de processo (Emergency Shutdown - ESD)': 'Downtime',
    'SSM - Parada emergencial de nível intermediário': 'Downtime',
    'SSM - Parada emergencial de nível maior': 'Downtime',
    'SSM - Falha na demanda total ou parcial de sistema crítico de segurança operacional': 'Downtime',
    'SSM - Falha de sistema crítico de segurança operacional': 'Downtime',
    'SSM - Reclassificação': 'Downtime',  # Normalmente envolve parada para reclassificação de risco
    
    # ========== INCÊNDIOS/EXPLOSÕES (classificação mista) ==========
    'SSM - Princípio de incêndio': 'Danos a Equipamentos',  # Pequeno dano + downtime
    'SSM - Incêndio significante': 'Danos a Equipamentos',  # Danos materiais significativos
    'SSM - Incêndio maior': 'Danos a Equipamentos',  # Danos materiais graves
    'SSM - Incêndio menor': 'Danos a Equipamentos',  # Danos materiais leves
    'SSM - Explosão mecânica': 'Danos a Equipamentos',  # Danos a equipamentos
    'SSM - Explosão de atmosfera explosiva': 'Danos a Equipamentos',  # Danos + potencial saúde
    'SSM - Detonação acidental de explosivos': 'Danos a Equipamentos',  # Danos a equipamentos/estruturas
    
    # ========== INFORMAÇÃO NÃO PADRONIZADA ==========
    'Informação não padronizada': 'Não Classificado'  # Removeremos depois
}

# Aplicar o mapeamento ao DataFrame
df_analysis['Categoria_Custo'] = df_analysis['Tipo_de_incidente'].map(mapeamento_completo)

## Custo_Incidente
<br>

#### Criação da coluna Custo_Incidente para inserir valores numéricos para comparação dos incidentes.

In [199]:
# Dicionários de gravidades para cada categoria
gravidade_downtime = {
    "LEVE": 1,
    "MODERADO": 9,
    "GRAVE": 30
}

custos_ambientais = {
    "LEVE": 3000.00,
    "MODERADO": 252500.00,
    "GRAVE": 25025000.00
}

custos_saude = {
    "LEVE": 2250.00,
    "MODERADO": 249750.00,
    "GRAVE": 25025000.00
}

custos_equip = {
    "LEVE": 45000.00,
    "MODERADO": 2250000.00,
    "GRAVE": 22500000.00
}

custos_perda_controle = {
    "LEVE": 225000.00,
    "MODERADO": 2250000.00,
    "GRAVE": 22500000.00
}

def calcular_custo(row):
    categoria = row["Categoria_Custo"]
    grav = row["DSC_GRAVIDADE_TIPO"]
    feridos_graves = row["Numero_de_feridos_graves"]

    # Downtime
    if categoria == "Downtime":
        return 149710.00 * gravidade_downtime[grav]

    # Custos Ambientais
    elif categoria == "Custos Ambientais":
        return custos_ambientais[grav]

    # Danos à Saúde (com multiplicação por número de feridos graves)
    elif categoria == "Danos a Saúde":
        custo_base = custos_saude[grav]

        if feridos_graves >= 2:
            return custo_base * feridos_graves
        else:
            return custo_base

    # Danos a Equipamentos
    elif categoria == "Danos a Equipamentos":
        return custos_equip[grav]

    # Perda de Controle
    elif categoria == "Perda de Controle/Critico":
        return custos_perda_controle[grav]

    # Não Classificado
    elif categoria == "Não Classificado":
        return 1

    else:
        return np.nan  # caso apareça alguma categoria inesperada


# Criar a coluna
df_analysis["Custo_Incidente"] = df_analysis.apply(calcular_custo, axis=1)

### Arrumando a ordem das colunas

In [200]:
ordem = [
    'Numero',
    'CNPJ',
    'Instalacao',
    'Tipo_Instalacao_Detalhado',
    'Proprietario_Instalacao',
    'Fonte_Classificacao',
    'Data_de_criacao',
    'DataHora_primeira_observacao',
    'DataHora_incidente',
    'Tipo_de_incidente',
    'Categoria_Custo',
    'Custo_Incidente',
    'DSC_GRAVIDADE_TIPO',
    'DSC_QUASE_ACIDENTE_ACIDENTE',
    'Numero_de_feridos_graves',
    'Numero_de_fatalidades'
]

In [201]:
df_analysis = df_analysis[ordem]
df_analysis.head(2)

,Numero,CNPJ,Instalacao,Tipo_Instalacao_Detalhado,Proprietario_Instalacao,Fonte_Classificacao,Data_de_criacao,DataHora_primeira_observacao,DataHora_incidente,Tipo_de_incidente,Categoria_Custo,Custo_Incidente,DSC_GRAVIDADE_TIPO,DSC_QUASE_ACIDENTE_ACIDENTE,Numero_de_feridos_graves,Numero_de_fatalidades
0,1307/000022,08926302000105,Ocean Quest,Navio de apoio logístico,Não identificado,Classificação avançada (confiança: Média) - Fr...,2013-07-09,2013-06-26 18:20:00,2013-06-26 18:20:00,SSM - Ferimento grave,Danos a Saúde,249750.0,MODERADO,Acidente,1,0
1,1307/000023,33000167000101,Cerrado,Outro,Não identificado,Classificação avançada (confiança: Muito Baixa...,2013-07-10,2013-07-06 07:20:00,2013-07-06 07:20:00,SSM - Ferimento grave,Danos a Saúde,249750.0,MODERADO,Acidente,1,0

## Faça o download do DataFrame limpo abaixo

In [202]:
# Faz o DOWNLOAD do DataFrame para o formato feather (leve e mantem os tipos)
df_analysis.to_feather("incidents_final_enriched_LIMPO.feather")

# Faz o DOWNLOAD do DataFrame para o formato feather (leve e mantem os tipos)
df_analysis.to_csv("incidents_final_enriched_LIMPO.csv")